name: Publish to PyPI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        environment:
            name: pypi
            url: https://pypi.org/p/jtf
                permissions:
            id-token: write
        steps:
            - name: Check out the code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Install build tools
              run: python -m pip install --upgrade build

            - name: Build package
              run: python -m build

            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
