name: Publish to PyPI

on:
    push:
        branches:
            - main # Triggers the workflow on commits to the main branch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12" # Specify the Python version you require

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build twine

            - name: Build the package
              run: python -m build

            - name: Publish to PyPI
              env:
                  TWINE_USERNAME: "__token__
              run: |
                  python -m twine upload --skip-existing dist/*
              with:
                twine: "latest"

